### ISSUE TITLE
Diagnostic Request

### ISSUE THREAD

**Issue by jwschmo** [openxc/openxc-python#82] opened 2016-09-04 02:59 UTC
OpenXC Python command:
openxc-diag add --message 0x7df --mode 0x3

Results in a dump of the entire buffer of CAN Frames.

**Comment by emarsman** [comment] 2016-09-06 14:31
This should fix that issue. https://github.com/openxc/openxc-python/tree/diagnosticResponseCleanup

**Comment by jwschmo** [comment] 2016-12-23 13:59
There isn't anything at that link.

**Comment by emarsman** [comment] 2017-01-04 16:52
Sorry, that branch got merged and deleted. Here is the PR #86 . It is currently in 'next' if you want to try it out.

**Comment by peplin** [comment] 2017-04-01 20:15
Since #86 is merged, I'll close this unless it's confirmed to not fix the bug. Thanks!

**Closed by peplin** 2017-04-01 20:15 UTC
